---
- name: Clean the environment
  hosts: db_servers
  become: true

  vars:
    db_packages:
      - mysql-server
      - mysql

  tasks:
    # Removed previously installed packages
    - name: Uninstall packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: absent
      loop: "{{ db_packages }}"
