---
- name: Verify role functionality
  hosts: all
  gather_facts: false
  vars:
    http_port: 9090
  tasks:
    - name: Check Apache service is running
      ansible.builtin.shell: systemctl is-active httpd
      register: service_status
    - name: Fail if Apache is not running
      ansible.builtin.fail:
        msg: "Apache is not running!"
      when: service_status.stdout != "active"


    - name: Hitting the web server
      ansible.builtin.shell: "curl localhost:{{ http_port }}"
      register: content

    - name: Fail if the server doesn't give the desired response 
      ansible.builtin.fail:
        msg: "The server is not behaving as expected!"
      when: '"Welcome to Ansible" not in content.stdout'

    - name: Printing the returned response
      ansible.builtin.debug:
        msg: "The returned response is: {{ content.stdout }}"


    
