---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Destroy Docker container
      containers.podman.podman_container:
        name: instance
        state: stopped
