---
- name: Clean the environment
  hosts: webservers
  become: true

  vars:
    web_packages:
      - httpd
      - firewalld


  tasks:
    # Removed previously installed packages
    - name: Uninstall packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: absent
      loop: "{{ web_packages }}"
